/*Schema*/
CREATE SCHEMA [PRIVATEFLIGHT]
GO

/*Table*/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [PRIVATEFLIGHT].[GREETINGTEXT](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[COUNTRYCODE] [char](3) NOT NULL,
	[TITLE] [nvarchar](50) NULL,
	[MESSAGETEXT] [nvarchar](1000) NULL,
	[STARTDATE] [datetimeoffset](7) NOT NULL,
	[ENDDATE] [datetimeoffset](7) NOT NULL,
	[IsActive] [bit] NULL,
	[MESSAGETYPE] [char](1) NOT NULL,
 CONSTRAINT [PK_GREETINGTEXT] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING ON
GO
CREATE UNIQUE NONCLUSTERED INDEX [UQ_MESSAGETYPE_STARTDATE_ENDDTAE] ON [PRIVATEFLIGHT].[GREETINGTEXT]
(
	[MESSAGETYPE] ASC,
	[STARTDATE] ASC,
	[ENDDATE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO


/*Stored Procedures*/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROC [PRIVATEFLIGHT].[usp_GREETINGSInsert]
    @COUNTRYCODE char(3),
    @MESSAGETYPE char(1),
    @STARTDATE datetime2(7),
    @ENDDATE datetime2(7) = NULL,
    @MESSAGETEXT nvarchar(1000) = NULL,
    @TITLE nvarchar(50) = NULL,
    @ISACTIVE int= 1
    
AS 
	SET NOCOUNT ON 
	SET XACT_ABORT ON  

	BEGIN TRAN
	
	INSERT INTO [PRIVATEFLIGHT].[GREETINGTEXT]
	(
        [COUNTRYCODE],
        [STARTDATE],
        [ENDDATE] ,
        [MESSAGETEXT] ,
        [MESSAGETYPE],
        [TITLE] ,
        [ISACTIVE] 
	)
	SELECT 
	@COUNTRYCODE ,
    @STARTDATE ,
    @ENDDATE ,
    @MESSAGETEXT ,
    @MESSAGETYPE,
    @TITLE ,
    @ISACTIVE 

	     
	COMMIT
GO

/*****************************/

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROC [PRIVATEFLIGHT].[usp_GREETINGSUPDATE]
    @ID BIGINT,
    @COUNTRYCODE char(3),
    @STARTDATE datetimeoffset,
    @ENDDATE datetimeoffset,
    @MESSAGETEXT nvarchar(1000) = NULL,
    @MESSAGETYPE char(1),
    @TITLE nvarchar(50) = NULL
   
    
AS 
	SET NOCOUNT ON 
	SET XACT_ABORT ON  

	BEGIN TRAN
	
	UPDATE [PRIVATEFLIGHT].[GREETINGTEXT]
	SET
        [COUNTRYCODE]=@COUNTRYCODE,
        [STARTDATE]=@STARTDATE,
        [ENDDATE] =@ENDDATE,
        [MESSAGETEXT]=@MESSAGETEXT ,
        [MESSAGETYPE]=@MESSAGETYPE,
        [TITLE] =@TITLE
       
	WHERE 
        [ID]=@ID
	     
	COMMIT
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROC [PRIVATEFLIGHT].[usp_GREETINGTEXTDELETE] 
    (@ID INT)
	
AS 
	SET NOCOUNT ON 
	SET XACT_ABORT ON  

 UPDATE [PRIVATEFLIGHT].[GREETINGTEXT]
    SET [ISACTIVE]=0
 WHERE [ID]=@ID
GO
/*****************************/

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROC [PRIVATEFLIGHT].[usp_GREETINGTEXTSelect] 
    (@COUNTRYCODE CHAR(3), @STARTDATE DATETIMEOFFSET=NULL)
	
AS 
	SET NOCOUNT ON 
	SET XACT_ABORT ON  

if(NULLIF(@COUNTRYCODE, '') IS NULL)
 BEGIN
    SELECT 
    [ID],
    [MESSAGETYPE],
    [COUNTRYCODE],
    [TITLE],
    [MESSAGETEXT],
    [STARTDATE],
    [ENDDATE]

    FROM [PRIVATEFLIGHT].[GREETINGTEXT]
    WHERE [ISACTIVE]=1
    order by ID desc
 END
 ELSE
    BEGIN
        SELECT 
        [ID],
        [MESSAGETYPE],
        [COUNTRYCODE],
        [TITLE],
        [MESSAGETEXT],
        [STARTDATE],
        [ENDDATE]

        FROM [PRIVATEFLIGHT].[GREETINGTEXT]
        WHERE [ISACTIVE]=1
            AND [COUNTRYCODE]=@COUNTRYCODE
            AND [STARTDATE]>=@STARTDATE
        order by ID desc
    END

GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROC [PRIVATEFLIGHT].[usp_GREETINGTEXTSelectGreeting] 
    (@COUNTRYCODE CHAR(3), @STARTDATE DATETIMEOFFSET=NULL)
	
AS 
	SET NOCOUNT ON 
	SET XACT_ABORT ON  
--starting with high precedence message multiple B type
if((SELECT COUNT(ID) FROM [PRIVATEFLIGHT].[GREETINGTEXT]  WHERE [ISACTIVE]=1 AND 
 [COUNTRYCODE]=@COUNTRYCODE AND [STARTDATE]>=@STARTDATE AND [ENDDATE]<=@STARTDATE AND [MESSAGETYPE]='B')>0)
    
 BEGIN
     SELECT 
            TOP (1)
        [MESSAGETEXT]    
        FROM [PRIVATEFLIGHT].[GREETINGTEXT]
        WHERE [ISACTIVE]=1 AND  [COUNTRYCODE]=@COUNTRYCODE AND @STARTDATE>=[STARTDATE] AND [MESSAGETYPE]='B'
        ORDER BY STARTDATE ASC
 END
 ELSE IF((SELECT COUNT(ID) FROM [PRIVATEFLIGHT].[GREETINGTEXT]  WHERE [ISACTIVE]=1 AND  
 [COUNTRYCODE]=@COUNTRYCODE AND [ENDDATE]=@STARTDATE AND [MESSAGETYPE]='A')>0)
    BEGIN
       SELECT 
            TOP (1) 
        [MESSAGETEXT]  

        FROM [PRIVATEFLIGHT].[GREETINGTEXT]  
        WHERE [ISACTIVE]=1 AND  [COUNTRYCODE]=@COUNTRYCODE AND [ENDDATE]<=@STARTDATE AND [MESSAGETYPE]='A'
        ORDER BY STARTDATE ASC
    END
ELSE IF((SELECT COUNT(ID) FROM [PRIVATEFLIGHT].[GREETINGTEXT]  WHERE [ISACTIVE]=1 AND  
 [COUNTRYCODE]=@COUNTRYCODE AND [ENDDATE]<=@STARTDATE AND [MESSAGETYPE] IN ('A','B'))>0)
BEGIN
      SELECT 
            TOP 1
        [MESSAGETEXT]   
        FROM [PRIVATEFLIGHT].[GREETINGTEXT]
        WHERE [ISACTIVE]=1 AND  [COUNTRYCODE]='AAA' ;
END

GO
